### ISSUE TITLE
No select box and resize handles showing or crop events triggering

### ISSUE THREAD

**Issue by nkeena** [pespantelis/vue-crop#3]
I have the directive installed globally like so..

``` javascript
import vueCrop from 'vue-crop'

Vue.directive('crop', vueCrop)
```

And referencing jCrop and jQuery:

``` html
<link rel="stylesheet" href="http://jcrop-cdn.tapmodo.com/v2.0.0-RC1/css/Jcrop.css" type="text/css">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="http://jcrop-cdn.tapmodo.com/v2.0.0-RC1/js/Jcrop.js"></script>
```

I'm then applying the directive to an image tag:

``` javascript
<img src="../../../assets/images/staff/thurner.jpg"
  width="600" height="400"
  v-crop:create="crop" v-crop:start="crop" v-crop:move="crop" v-crop:end="crop" />
```

And setup a method to listen for the events:

``` javascript
crop: function (event, selection, coordinates) {
      console.log(event)
      this.coords = coordinates
    },
```

But the events never seem to fire and no cropping box or handles appear on the image. What am I missing?

**Comment by pespantelis** [comment]
Because the `Jcrop` exists on the `global` scope, the same should be for the `VueCrop`. :)

**Comment by nkeena** [comment]
I'm afraid I don't understand what you mean. The directive is installed globally. I've tried pulling jcrop in using a module import with webpack but it still doesn't work. :(

Do you have an example of using VueCrop with a webpack project?
